# To build book locally...

# Make sure quarto is installed (this should already have been done automatically)
# Run the "quarto preview" command in terminal
# (optionally a file name such as index.qmd to render a specific file)

# This will render the entire website locally which could take a while if it is the first time rendering.
# If shown error about not having quarto installed run this command in Command Prompt (navigate to the primer folder with cd)

# If there are no errors in the files then this should locally preview the entire primer
# Take a look around to make sure that you're changes are working (even if there are no errors)

# Need to check if we can set junk to output-dir instead of docs like for bookdown

# Below is the code for the quarto.yml (mostly taken by referencing example books)
# Good example book: https://github.com/jjallaire/hopr
# Specifically referenced the "_quarto.yml" file

# Note to self: Always ADD MORE COMMENTS!

project:
  type: book
  output-dir: docs

# Tryed to use pre-render instead before_chapter script
# Gave up on finding quarto eqivalent of before_chapter_script and after
# pre/post-render work differently from bookdown before_chapter_script (not working)
# For more info see: https://community.rstudio.com/t/cannot-get-quarto-pre-render-to-work/143566
# Or my RS Community query: https://community.rstudio.com/t/quarto-book-start-equivalent/144196


# Most items below taken from old bookdown primer's index.rmd yml header (needs to be here for quarto)
# All general info under the book header

# Still working on references in bibliography/references page

book:
  title: "Preceptor's Primer for Bayesian Data Science"
  author: "David Kane"
  bibliography: [bib/references.bib, bib/packages.bib]
  biblio-style: apalike
  link-citations: yes
  nocite: '@*'
  colorlinks: yes
  lot: false
  lof: false
  always_allow_html: yes
  graphics: yes
  chapters:
    - index.qmd
    - 00-getting-started.qmd
    - 01-visualization.qmd
    - 02-wrangling.qmd
    - 03-data.qmd
    - 04-rubin-causal-model.qmd
    - 05-probability.qmd
    - 06-one-parameter.qmd
    - 07-two-parameters.qmd
    - 08-three-parameters.qmd
    - 09-four-parameters.qmd
    - 10-five-parameters.qmd
    - 11-n-parameters.qmd
    - 12-case-studies.qmd
    - tools.qmd
    - functions.qmd
    - animation.qmd
    - set-up.qmd
    - references.qmd

# No special chapter's inside of others currently

# Numbers show up highlighted in file names?

# Default quarto formatting for books/other documents below
# Change theme to more closely match current primer? Need to check available themes

# Optionally add more formatting options/code-link?

format:
  html:
    theme: cosmo
    code-link: true
