project:
  type: book
  output-dir: docs
  
book:
  title: "Preceptor's Primer for Bayesian Data Science"
  author: "David Kane"
  bibliography: [bib/references.bib, bib/packages.bib]
  biblio-style: apalike
  link-citations: yes
  nocite: '@*'
  colorlinks: yes
  lot: false
  lof: false
  always_allow_html: yes
  graphics: yes
  chapters:
    - index.qmd
    - 00-getting-started.qmd
    - 01-visualization.qmd
    - 02-wrangling.qmd
    - 03-data.qmd
    - 04-rubin-causal-model.qmd
    - 05-probability.qmd
    - 06-one-parameter.qmd
    - 07-two-parameters.qmd
    - 08-three-parameters.qmd
    - 09-four-parameters.qmd
    - 10-five-parameters.qmd
    - 11-n-parameters.qmd
    - 12-case-studies.qmd
    - tools.qmd
    - functions.qmd
    - animation.qmd
    - set-up.qmd
    - references.qmd
    
format:
  html: 
    theme: cosmo
    code-link: true
